### PR TITLE
Fix 15 error activation if no dependencis are installed

### LINKED ISSUE #15: Error activation if no dependencies are installed
If no dependencies installed then this addon do not activate itself or reset Blender.

image

### PR DESCRIPTION
**Pull request by satabol**
fix #15 

If now open3d library installed then you can see Sverchok-Open3D activated anyway:

image

### CODE REVIEW

**Comment by satabol** [comment]
@vicdoval Can you see when you’re comfortable?

Mostly just unindentations.

**Comment by vicdoval** [comment]
So, if you dont have open3d you can not enable the addon?
And if you have it the it is enabled automatically?

What happens if you open a tree from someone that uses sv-open3d and you dont have  the library??

**Comment by satabol** [comment]
> So, if you dont have open3d you can not enable the addon? And if you have it the it is enabled automatically?

This PR fix this situation now. If user has no open3d library installed then addon activated anyway and user can open settings and install open3d library by addon settings.

>What happens if you open a tree from someone that uses sv-open3d and you dont have the library??

It is safely to open that nodes:

image

**Comment by satabol** [comment]
> What happens if you open a tree from someone that uses sv-open3d and you dont have the library??

Also all menu items are blocked:

image

This feature was created by @Soluserg in Sverchok and I apply this only.

**Comment by vicdoval** [comment]
Awesome!
Everything seems to work.
Is it ready to merge?

**Comment by satabol** [comment]
Yes.

**Pull request merged**
