### PR TITLE
fix activation for sverchok 1.2/1.3

### PR DESCRIPTION
**Pull request by satabol**
- updated __init__
- updated nodes

### CODE REVIEW

**Comment by vicdoval** [comment]
Hi satabol! 
Thanks for your PR, I'm almost out of the game lately and I was always waiting to open3d to update their pip library to python 3... not sure if they had done it now.

When I tried your PR with blender 4.02 and the last Sverchok (from today)  I get this message...

```
from sverchok.utils.dummy_nodes import add_dummy
ModuleNotFoundError: No module named 'sverchok.utils.dummy_nodes'
```

**Comment by satabol** [comment]
I see. Sverchok is not work with Blender 4.x for a while. Can you test it with Blender 3.6.x ? Also Open3D must be installed already. Dummy object do not exists in Sverchok now. I think I fix it later. There are some users who want to get it work and I want to test this fix with them (I have no info for tests). I think they have Open3D library installed.

A command for install Open3D in Blender manually is:
"D:\Install\Blender\blender-3.6.9-windows-x64\3.6\python\bin\python.exe" -m pip install open3d
LTS Version of blender is: https://www.blender.org/download/lts/3-6/

**Comment by vicdoval** [comment]
It works!! 
Before there use to be one menu called open3d and it contained the three submenus (I use to have a keystroke for that menu that was never added by default but was pretty handle). If that is not possible to implement changing the names of the menus adding O3D could be another possibility

**Comment by vicdoval** [comment]
this is how right now works with 2.92 and the https://github.com/vicdoval/sverchok/tree/extra_addons_support.
image

**Comment by satabol** [comment]
Ok. I need some time.

**Comment by satabol** [comment]
Is it look good?
image
I'm on finish line...)))

**Comment by vicdoval** [comment]
Looks great!

**Comment by satabol** [comment]
How to assign icons on group menu:
image

Now no icon on root elem. I found some issue in Sverchok and fix it too: https://github.com/nortikin/sverchok/pull/5087
If Sverchok PR will merged then root icon will shown:

image
image

**Comment by vicdoval** [comment]
great work mate!

I was using the Random num generator Icon, but I'm fine with the blender one (probably is more consistent)
image

**Comment by vicdoval** [comment]
So do you consider it ready? As far as I see everything is ready

**Comment by satabol** [comment]
Lets try? )))

**Comment by satabol** [comment]
I test update too. It is work:

image

**Comment by satabol** [comment]
Can you apply this PR ?

**Comment by vicdoval** [comment]
Thank you satabol and congratulations!!

**Pull request merged**
